import { motion } from 'motion/react';
import { ArrowRight } from 'lucide-react';

interface GraduationPageProps {
  characterName: string;
  storylineTitle?: string;
  onComplete: () => void;
}

export function GraduationPage({ characterName, storylineTitle, onComplete }: GraduationPageProps) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-400 via-pink-400 to-blue-400 flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white rounded-3xl shadow-2xl w-full max-w-3xl p-4"
      >
        {/* Header */}
        <div className="text-center mb-2">
          <h2 className="text-gray-800 mb-1">🎓 Graduation Day!</h2>
          <p className="text-gray-600 text-xs">Congratulations on completing your studies!</p>
        </div>

        {/* Storyline Title Banner - NEW */}
        {storylineTitle && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="mb-2 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white rounded-xl p-3 text-center border-2 border-purple-300 shadow-lg"
          >
            <p className="text-[10px] uppercase tracking-wider opacity-90 mb-0.5">Your Story Begins</p>
            <h3 className="text-gray-100">{storylineTitle}</h3>
          </motion.div>
        )}

        {/* Video Placeholder - Smaller */}
        {/* This is placeholder for video of graduation at the intro. This video is generated by AI. */}
        <div className="mb-2">
          <div className="aspect-video bg-gradient-to-br from-indigo-100 to-purple-100 rounded-xl flex items-center justify-center border-2 border-indigo-200 relative overflow-hidden">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 2 }}
              className="text-center"
            >
              <motion.div
                animate={{ 
                  scale: [1, 1.2, 1],
                  rotate: [0, 10, -10, 0]
                }}
                transition={{ 
                  duration: 3,
                  repeat: Infinity,
                  repeatType: "reverse"
                }}
                className="text-4xl mb-1"
              >
                🎓
              </motion.div>
              <p className="text-gray-600 text-[10px]">
                [ AI Graduation Video ]
              </p>
            </motion.div>

            {/* Confetti Animation - Reduced */}
            <div className="absolute inset-0 pointer-events-none">
              {[...Array(10)].map((_, i) => (
                <motion.div
                  key={i}
                  initial={{ y: -20, x: Math.random() * 100 + '%', opacity: 1 }}
                  animate={{ 
                    y: '100vh',
                    rotate: Math.random() * 360,
                    opacity: 0
                  }}
                  transition={{ 
                    duration: Math.random() * 3 + 2,
                    delay: Math.random() * 2,
                    repeat: Infinity
                  }}
                  className="absolute text-xs"
                  style={{
                    left: `${Math.random() * 100}%`
                  }}
                >
                  {['🎉', '🎊', '⭐', '✨', '🌟'][Math.floor(Math.random() * 5)]}
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* Graduation Message */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="bg-gradient-to-br from-yellow-50 to-orange-50 rounded-xl p-3 mb-2 border-2 border-yellow-200"
        >
          <p className="text-center text-gray-800 text-xs leading-relaxed">
            "You are now <span className="font-bold text-purple-600">18 years old</span> and graduated, <span className="font-bold text-pink-600">{characterName}</span>! 
            Your exciting adult life with finance challenges starts here."
          </p>
        </motion.div>

        {/* Achievement Badges */}
        <div className="grid grid-cols-3 gap-2 mb-3">
          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 1 }}
            className="bg-blue-50 rounded-lg p-2 text-center border-2 border-blue-200"
          >
            <div className="text-xl">📚</div>
            <p className="text-gray-700 text-[10px]">Education Complete</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 1.2 }}
            className="bg-green-50 rounded-lg p-2 text-center border-2 border-green-200"
          >
            <div className="text-xl">🎯</div>
            <p className="text-gray-700 text-[10px]">Ready for Life</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 1.4 }}
            className="bg-purple-50 rounded-lg p-2 text-center border-2 border-purple-200"
          >
            <div className="text-xl">💰</div>
            <p className="text-gray-700 text-[10px]">Financial Journey</p>
          </motion.div>
        </div>

        {/* Start Game Button */}
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.6 }}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={onComplete}
          className="w-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white py-2.5 rounded-xl shadow-lg transition-all flex items-center justify-center gap-2 text-sm"
        >
          <span>Start Your Financial Journey!</span>
          <ArrowRight className="w-4 h-4" />
        </motion.button>

        {/* Progress Indicator */}
        <div className="mt-2 flex items-center justify-center gap-1.5">
          <div className="w-1.5 h-1.5 rounded-full bg-purple-500"></div>
          <div className="w-1.5 h-1.5 rounded-full bg-purple-500"></div>
          <div className="w-1.5 h-1.5 rounded-full bg-purple-500"></div>
          <div className="w-1.5 h-1.5 rounded-full bg-purple-500"></div>
        </div>
        <p className="text-center text-gray-500 text-[10px] mt-1">Step 4 of 4 - Complete!</p>
      </motion.div>
    </div>
  );
}